### PR TITLE
Fix #47: Add implicit grant

### LINKED ISSUE #47: Implicit grant type
Is there already [implicit grant type](https://tools.ietf.org/html/rfc6749#section-1.3.2) support or work around available? I can provide one if there is none already.

### PR DESCRIPTION
**Pull request by satabin**
Implementation of the implicit grant.

The handler that receives a request must find the user by authenticating
him in any way the application requires it.
The user authentication is done using the received grant request with
all headers and parameters.

### CODE REVIEW

**Comment by satabin** [comment]
I am not sure this is the way to do implicit grant, but that's how I understand the RFC.
Any comments and corrections are welcome.

**Comment by tsuyoshizawa** [comment]
Awesome. I will check this PR later.

**Comment by satabin** [comment]
There seems to be a problem with the travis build. Sbt is not found and leads to test failure. On my computer all tests are ok for both scala versions.

**Comment by tsuyoshizawa** [comment]
The problem is because of https://github.com/travis-ci/travis-ci/issues/4527

**Comment by satabin** [comment]
OK thanks

**Pull request merged**
